import Head from 'next/head';
import styles from '../styles/Home.module.css'
import Image from 'next/image'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Página Principal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>Hello, World!</h1>
        <Image 
          src="/images/city.jpg" 
          width="400px" 
          height="500px" 
          alt="Cidade a noite"
        />
      </main>

      
    </div>
  )
}
